# CLASSIFICATION: UNCLASSIFIED
{{ if .Values.secretProviderClass.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "rtsa-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rtsa-service.labels" . | nindent 4 }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: {{ .Values.serviceAccount.workloadIdentityClientId | quote }}
    keyvaultName: {{ .Values.secretProviderClass.keyvaultName | quote }}
    tenantId: {{ .Values.secretProviderClass.tenantId | quote }}
    objects: |
      array:
        {{- range .Values.secretProviderClass.objects }}
        - |
          objectName: {{ .objectName }}
          objectType: {{ .objectType }}
          {{- if .objectAlias }}
          objectAlias: {{ .objectAlias }}
          {{- end }}
        {{- end }}
  {{- if .Values.secretProviderClass.syncSecret.enabled }}
  secretObjects:
    - secretName: {{ .Values.secretProviderClass.syncSecret.name | default (include "rtsa-service.fullname" .) }}
      type: Opaque
      data:
        {{- range .Values.secretProviderClass.objects }}
        - objectName: {{ .objectAlias | default .objectName }}
          key: {{ .objectAlias | default .objectName }}
        {{- end }}
  {{- end }}
{{- end }}
