// CLASSIFICATION: UNCLASSIFIED
// src/workers/data-worker.ts — Data Worker (Phase 2: WebTransport + Wasm decoder)
//
// Responsibilities:
//   1. Accept SharedArrayBuffer via postMessage on init
//   2. Connect to the Go WebTransport server and receive FlatBuffer datagrams
//   3. Decode each 128-byte record via the Rust Wasm decoder into the SAB
//   4. Support batch datagrams (up to 9 × 128 bytes per QUIC datagram)
//   5. Implement exponential-backoff reconnection
//   6. Report connection status and decode statistics to the main thread
//
// Reference: docs/sdlc_guidelines/08_tech_specific/webtransport_guidelines.md §6

// ── Constants matching the SAB layout (sab.ts) ────────────────────────────────
const RECORD_SIZE = 128;                         // bytes per FlatBuffer track record
const HEADER_SIZE = 4096;                        // bytes for SAB header
const DIRTY_BITFIELD_SIZE = 8192;                // bytes for dirty bitfield
const TRACK_DATA_OFFSET = HEADER_SIZE + DIRTY_BITFIELD_SIZE; // = 12288
const HEADER_OFFSET_ACTIVE_TRACK_COUNT = 0;     // uint32 index in header Uint32Array
const HEADER_OFFSET_MAX_SLOTS = 2;              // uint32 index in header Uint32Array
const MAX_BATCH_SIZE = 9;                        // max records per datagram (9×128=1152<MTU)
const MAX_BACKOFF_MS = 30_000;
const BASE_BACKOFF_MS = 1_000;
const MOCK_INTERVAL_MS = 16; // ~60 Hz mock update rate
const STATS_INTERVAL_MS = 1_000;

// ── Message types ─────────────────────────────────────────────────────────────

interface InitMessage {
  type: "init";
  sab: SharedArrayBuffer;
  /** WebTransport server URL (e.g. https://rtsa.mil.ca:4443/wt?token=...). */
  url?: string;
}

interface StatusMessage {
  type: "connection_status";
  connected: boolean;
  /** RTT estimate in ms derived from update_epoch_ms delta; -1 if disconnected. */
  latency: number;
}

interface StatsMessage {
  type: "stats";
  datagramsReceived: number;
  recordsDecoded: number;
  decodeErrors: number;
}

// ── Module state ──────────────────────────────────────────────────────────────

let sab: SharedArrayBuffer | null = null;
let sabHeader: Uint32Array | null = null;
let trackData: Uint8Array | null = null;
let maxSlots = 0;
let slotIndex = 0;
let mockIntervalId: ReturnType<typeof setInterval> | null = null;
let statsIntervalId: ReturnType<typeof setInterval> | null = null;

// Decode statistics (reset on each stats flush)
let datagramsReceived = 0;
let recordsDecoded = 0;
let decodeErrors = 0;

// ── Wasm decoder (optional — fallback to direct copy if not loaded) ───────────

interface WasmDecoder {
  write_slot_from_datagram(
    sab_slice: Uint8Array,
    slot_index: number,
    max_slots: number,
    datagram: Uint8Array,
  ): boolean;
}

let wasmDecoder: WasmDecoder | null = null;

/**
 * Attempt to load the Rust Wasm decoder module.
 * Falls back gracefully to a direct byte-copy if loading fails.
 *
 * Reference: web-cop-gpu/wasm-decoder/src/lib.rs
 */
async function loadWasmDecoder(): Promise<void> {
  try {
    // Dynamic import of the Wasm module generated by wasm-pack.
    // The module is expected at the wasm-decoder package path.
    const mod = await import(
      /* @vite-ignore */ new URL("../../wasm-decoder/pkg/wasm_decoder.js", import.meta.url).href
    );
    await mod.default(); // initialise the Wasm binary
    wasmDecoder = mod as WasmDecoder;
  } catch (_err) {
    // Wasm module not yet compiled or unavailable — use direct copy fallback.
    wasmDecoder = null;
  }
}

// ── Record writing ────────────────────────────────────────────────────────────

/**
 * Decode a single 128-byte record into the SAB at the given slot.
 * Uses the Rust Wasm decoder if available, otherwise falls back to direct copy.
 */
function writeRecordToSlot(record: Uint8Array, slot: number): boolean {
  if (!trackData || slot >= maxSlots) return false;
  if (record.byteLength < RECORD_SIZE) return false;

  if (wasmDecoder) {
    return wasmDecoder.write_slot_from_datagram(trackData, slot, maxSlots, record);
  }

  // Fallback: direct copy at documented SAB offset
  const offset = slot * RECORD_SIZE;
  trackData.set(record.subarray(0, RECORD_SIZE), offset);
  return true;
}

/**
 * Process a batch datagram containing 1–9 concatenated 128-byte records.
 * Each record is decoded and written to successive SAB slots.
 */
function processDatagram(datagram: Uint8Array): void {
  if (!sabHeader || !trackData) return;

  const recordCount = Math.min(
    Math.floor(datagram.byteLength / RECORD_SIZE),
    MAX_BATCH_SIZE,
  );

  let decoded = 0;
  for (let i = 0; i < recordCount; i++) {
    const recordView = new Uint8Array(
      datagram.buffer,
      datagram.byteOffset + i * RECORD_SIZE,
      RECORD_SIZE,
    );
    const slot = slotIndex % maxSlots;
    if (writeRecordToSlot(recordView, slot)) {
      slotIndex = (slotIndex + 1) % maxSlots;
      decoded++;
    } else {
      decodeErrors++;
    }
  }

  if (decoded > 0) {
    // Update active_track_count in the SAB header (non-atomic write is
    // acceptable here — the render worker treats this as advisory).
    const currentCount = Atomics.load(sabHeader, HEADER_OFFSET_ACTIVE_TRACK_COUNT);
    const newCount = Math.min(currentCount + decoded, maxSlots);
    Atomics.store(sabHeader, HEADER_OFFSET_ACTIVE_TRACK_COUNT, newCount);
    recordsDecoded += decoded;
  }
}

// ── Mock data (stub mode — no URL provided) ───────────────────────────────────

/**
 * Write a mock 128-byte track record into the SharedArrayBuffer.
 * Used for testing the data flow before a real WebTransport server is available.
 *
 * Field offsets match wasm-decoder/src/lib.rs offsets module.
 */
function writeMockRecord(slot: number): void {
  if (!trackData || slot >= maxSlots) return;

  const offset = slot * RECORD_SIZE;
  const view = new DataView(trackData.buffer, trackData.byteOffset + offset, RECORD_SIZE);

  const lon = (Math.random() * 2 - 1) * Math.PI;
  const lat = (Math.random() * 2 - 1) * (Math.PI / 2);
  view.setFloat32(0x00, lon, true);                           // longitude
  view.setFloat32(0x04, lat, true);                           // latitude
  view.setFloat32(0x08, 0, true);                             // course
  view.setFloat32(0x0c, 10, true);                            // speed m/s
  view.setFloat32(0x10, 1000, true);                          // altitude meters
  view.setUint32(0x14, slot, true);                           // track_id_hash
  view.setUint32(0x18, 1, true);                              // source_bitmap
  view.setUint32(0x1c, 1, true);                              // classification_level
  view.setUint32(0x20, 0, true);                              // threat_level = Unknown
  view.setUint32(0x24, 0, true);                              // icon_index
  view.setUint32(0x28, 0, true);                              // alert_flags
  view.setUint32(0x2c, Date.now() & 0xffffffff, true);        // update_epoch_ms
}

function startMockUpdates(): void {
  if (mockIntervalId !== null) return;

  mockIntervalId = setInterval(() => {
    if (!trackData || !sabHeader) return;
    writeMockRecord(slotIndex % maxSlots);
    slotIndex = (slotIndex + 1) % maxSlots;
    Atomics.store(sabHeader, HEADER_OFFSET_ACTIVE_TRACK_COUNT,
      Math.min(slotIndex, maxSlots));
  }, MOCK_INTERVAL_MS);

  postMessage({ type: "connection_status", connected: true, latency: 0 } satisfies StatusMessage);
}

function stopMockUpdates(): void {
  if (mockIntervalId !== null) {
    clearInterval(mockIntervalId);
    mockIntervalId = null;
  }
}

// ── Statistics reporting ──────────────────────────────────────────────────────

function startStatsReporting(): void {
  if (statsIntervalId !== null) return;
  statsIntervalId = setInterval(() => {
    postMessage({
      type: "stats",
      datagramsReceived,
      recordsDecoded,
      decodeErrors,
    } satisfies StatsMessage);
    datagramsReceived = 0;
    recordsDecoded = 0;
    decodeErrors = 0;
  }, STATS_INTERVAL_MS);
}

function stopStatsReporting(): void {
  if (statsIntervalId !== null) {
    clearInterval(statsIntervalId);
    statsIntervalId = null;
  }
}

// ── WebTransport connection ───────────────────────────────────────────────────

/**
 * Connect to a WebTransport server with exponential backoff retry.
 * Never returns — loops indefinitely until the worker is terminated.
 *
 * Reference: webtransport_guidelines.md §6.3
 */
async function connectWithRetry(url: string): Promise<void> {
  let attempt = 0;

  while (true) {
    try {
      await connectWebTransport(url);
      // Clean connection close — reset attempt counter
      attempt = 0;
    } catch (_err) {
      attempt++;
      const delay = Math.min(BASE_BACKOFF_MS * Math.pow(2, attempt), MAX_BACKOFF_MS);
      postMessage({ type: "connection_status", connected: false, latency: -1 } satisfies StatusMessage);
      await sleep(delay);
    }
  }
}

/**
 * Establish a WebTransport connection and process datagrams until closed.
 *
 * Datagram format: N × 128-byte FlatBuffer records (N = 1–9).
 * Reference: webtransport_guidelines.md §4.2, §6.1
 */
async function connectWebTransport(url: string): Promise<void> {
  const transport = new WebTransport(url);
  await transport.ready;

  postMessage({ type: "connection_status", connected: true, latency: 0 } satisfies StatusMessage);
  startStatsReporting();

  const reader = transport.datagrams.readable.getReader();

  try {
    while (true) {
      const { value: datagram, done } = await reader.read();
      if (done) break;
      if (!datagram || !trackData) continue;

      datagramsReceived++;
      processDatagram(new Uint8Array(datagram));
    }
  } finally {
    reader.releaseLock();
    stopStatsReporting();
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// ── Message handler ───────────────────────────────────────────────────────────

self.addEventListener("message", (event: MessageEvent<InitMessage>) => {
  const msg = event.data;

  if (msg.type === "init") {
    sab = msg.sab;

    // Parse SAB header — max_slots is at uint32 index HEADER_OFFSET_MAX_SLOTS (= 2)
    sabHeader = new Uint32Array(sab, 0, HEADER_SIZE / 4);
    maxSlots = sabHeader[HEADER_OFFSET_MAX_SLOTS];

    // Track data starts immediately after the header + dirty bitfield
    trackData = new Uint8Array(sab, TRACK_DATA_OFFSET);

    if (msg.url) {
      // Phase 2 hot path: real WebTransport connection
      loadWasmDecoder().then(() => {
        connectWithRetry(msg.url!).catch((_err) => {
          postMessage({ type: "connection_status", connected: false, latency: -1 } satisfies StatusMessage);
        });
      });
    } else {
      // Stub/dev mode: generate mock data for pipeline testing
      startMockUpdates();
    }
  }
});

// Clean up on Worker termination
self.addEventListener("close", () => {
  stopMockUpdates();
  stopStatsReporting();
});
