// CLASSIFICATION: UNCLASSIFIED
// src/workers/data-worker.ts — Data Worker (Phase 2: WebTransport + Wasm decoder)
//
// Responsibilities:
//   1. Accept SharedArrayBuffer via postMessage on init
//   2. Connect to the Go WebTransport server and receive FlatBuffer datagrams
//   3. Decode each 128-byte record via the Rust Wasm decoder into the SAB
//   4. Support batch datagrams (up to 9 × 128 bytes per QUIC datagram)
//   5. Implement exponential-backoff reconnection
//   6. Report connection status and decode statistics to the main thread
//   7. Notify the main thread when the JWT is nearing expiry and reconnect
//      with a refreshed token when one is supplied.
//
// Reference: docs/sdlc_guidelines/08_tech_specific/webtransport_guidelines.md §6

// ── Constants matching the SAB layout (sab.ts) ────────────────────────────────
const RECORD_SIZE = 128;                         // bytes per FlatBuffer track record
const HEADER_SIZE = 4096;                        // bytes for SAB header
const DIRTY_BITFIELD_SIZE = 8192;                // bytes for dirty bitfield
const TRACK_DATA_OFFSET = HEADER_SIZE + DIRTY_BITFIELD_SIZE; // = 12288
const HEADER_OFFSET_ACTIVE_TRACK_COUNT = 0;     // uint32 index in header Uint32Array
const HEADER_OFFSET_MAX_SLOTS = 2;              // uint32 index in header Uint32Array
const MAX_BATCH_SIZE = 9;                        // max records per datagram (9×128=1152<MTU)
const MAX_BACKOFF_MS = 30_000;
const BASE_BACKOFF_MS = 1_000;
const MOCK_INTERVAL_MS = 16; // ~60 Hz mock update rate
const MOCK_BATCH_SIZE = 1_000; // records written per tick — fills 50k slots in ~800 ms
const STATS_INTERVAL_MS = 1_000;

import {
    buildTransportUrl,
    getJwtExpiryMs,
    writeMockRecord as writeMockRecordLogic,
    writeRecordToSlot as writeRecordToSlotLogic,
    type WasmDecoder,
} from "./data-worker-logic";

// ── Message types ─────────────────────────────────────────────────────────────

interface InitMessage {
  type: "init";
  sab: SharedArrayBuffer;
  /** WebTransport server URL (e.g. https://rtsa.mil.ca:4443/wt). */
  url?: string;
  /**
   * Short-lived JWT for WebTransport authentication.
   * Appended as `?token=<jwt>` to the WebTransport URL.
   * NEVER log this value. (SDLC Rule 5)
   */
  token?: string;
}

interface TokenRefreshMessage {
  type: "token-refresh";
  /**
   * Refreshed JWT supplied by the main thread.
   * The worker closes the current transport and reconnects with this token.
   * NEVER log this value. (SDLC Rule 5)
   */
  token: string;
}

type WorkerInboundMessage = InitMessage | TokenRefreshMessage;

interface StatusMessage {
  type: "connection_status";
  connected: boolean;
  /** RTT estimate in ms derived from update_epoch_ms delta; -1 if disconnected. */
  latency: number;
}

interface StatsMessage {
  type: "stats";
  datagramsReceived: number;
  recordsDecoded: number;
  decodeErrors: number;
}

/** Sent when the current JWT is ~60 s from expiry. */
interface TokenExpiringMessage {
  type: "token-expiring";
}

import { FusionStatsUpdateMessage } from "./shared-protocol";

// ── Module state ──────────────────────────────────────────────────────────────

let sab: SharedArrayBuffer | null = null;
let sabHeader: Uint32Array | null = null;
let trackData: Uint8Array | null = null;
let maxSlots = 0;
let slotIndex = 0;
let mockIntervalId: ReturnType<typeof setInterval> | null = null;
let statsIntervalId: ReturnType<typeof setInterval> | null = null;

// Current connection parameters (updated on token refresh)
let currentUrl: string | undefined = undefined;
let currentToken: string | undefined = undefined;

// Active transport — closed on token refresh to trigger reconnect
let activeTransport: WebTransport | null = null;

// Token-expiry timer
let tokenExpiryTimerId: ReturnType<typeof setTimeout> | null = null;

// Decode statistics (reset on each stats flush)
let datagramsReceived = 0;
let recordsDecoded = 0;
let decodeErrors = 0;

// ── Wasm decoder (optional — fallback to direct copy if not loaded) ───────────

// WasmDecoder interface is imported from data-worker-logic.ts.

let wasmDecoder: WasmDecoder | null = null;

/**
 * Attempt to load the Rust Wasm decoder module.
 * Falls back gracefully to a direct byte-copy if loading fails.
 *
 * The Wasm module is copied to public/wasm/ by the prebuild script so that
 * it is served as a static asset from the same origin in production builds.
 *
 * Reference: web-cop-gpu/wasm-decoder/src/lib.rs
 */
async function loadWasmDecoder(): Promise<void> {
  try {
    // Dynamic import of the Wasm module generated by wasm-pack.
    // The module is served from /wasm/ (copied by the prebuild script).
    const mod = await import(
      /* @vite-ignore */ new URL("/wasm/wasm_decoder.js", self.location.href).href
    );
    await mod.default(); // initialise the Wasm binary
    wasmDecoder = mod as WasmDecoder;
  } catch (_err) {
    // Wasm module not yet compiled or unavailable — use direct copy fallback.
    wasmDecoder = null;
  }
}

// ── Record writing ────────────────────────────────────────────────────────────

/**
 * Decode a single 128-byte record into the SAB at the given slot.
 * Delegates to the pure writeRecordToSlot logic in data-worker-logic.ts.
 */
function writeRecordToSlot(record: Uint8Array, slot: number): boolean {
  if (!trackData) return false;
  return writeRecordToSlotLogic(trackData, slot, maxSlots, record, wasmDecoder);
}

/**
 * Process a batch datagram containing 1–9 concatenated 128-byte records.
 * Each record is decoded and written to successive SAB slots.
 */
function processDatagram(datagram: Uint8Array): void {
  if (!sabHeader || !trackData) return;

  const recordCount = Math.min(
    Math.floor(datagram.byteLength / RECORD_SIZE),
    MAX_BATCH_SIZE,
  );

  let decoded = 0;
  for (let i = 0; i < recordCount; i++) {
    const recordView = new Uint8Array(
      datagram.buffer,
      datagram.byteOffset + i * RECORD_SIZE,
      RECORD_SIZE,
    );
    const slot = slotIndex % maxSlots;
    if (writeRecordToSlot(recordView, slot)) {
      slotIndex = (slotIndex + 1) % maxSlots;
      decoded++;
    } else {
      decodeErrors++;
    }
  }

  if (decoded > 0) {
    // Update active_track_count in the SAB header (non-atomic write is
    // acceptable here — the render worker treats this as advisory).
    const currentCount = Atomics.load(sabHeader, HEADER_OFFSET_ACTIVE_TRACK_COUNT);
    const newCount = Math.min(currentCount + decoded, maxSlots);
    Atomics.store(sabHeader, HEADER_OFFSET_ACTIVE_TRACK_COUNT, newCount);
    recordsDecoded += decoded;
  }
}

// ── Mock data (stub mode — no URL provided) ───────────────────────────────────

/**
 * Write a mock 128-byte track record into the SharedArrayBuffer.
 * Delegates to the pure writeMockRecord logic in data-worker-logic.ts.
 */
function writeMockRecord(slot: number): void {
  if (!trackData) return;
  writeMockRecordLogic(trackData, slot, maxSlots);
}

function startMockUpdates(): void {
  if (mockIntervalId !== null) return;

  mockIntervalId = setInterval(() => {
    if (!trackData || !sabHeader) return;
    const batchCount = Math.min(MOCK_BATCH_SIZE, maxSlots);
    for (let i = 0; i < batchCount; i++) {
      writeMockRecord(slotIndex);
      slotIndex = (slotIndex + 1) % maxSlots;
    }
    const currentCount = Atomics.load(sabHeader, HEADER_OFFSET_ACTIVE_TRACK_COUNT);
    Atomics.store(
      sabHeader,
      HEADER_OFFSET_ACTIVE_TRACK_COUNT,
      Math.min(currentCount + batchCount, maxSlots),
    );
  }, MOCK_INTERVAL_MS);

  postMessage({ type: "connection_status", connected: true, latency: 0 } satisfies StatusMessage);
}

function stopMockUpdates(): void {
  if (mockIntervalId !== null) {
    clearInterval(mockIntervalId);
    mockIntervalId = null;
  }
}

// ── Statistics reporting ──────────────────────────────────────────────────────

function startStatsReporting(): void {
  if (statsIntervalId !== null) return;
  statsIntervalId = setInterval(() => {
    postMessage({
      type: "stats",
      datagramsReceived,
      recordsDecoded,
      decodeErrors,
    } satisfies StatsMessage);

    // Also report higher-level Fusion stats for the Ops Commander dashboard.
    // This is the O(N) aggregation performed in Rust Wasm to keep the Main Thread free.
    reportFusionStats();

    datagramsReceived = 0;
    recordsDecoded = 0;
    decodeErrors = 0;
  }, STATS_INTERVAL_MS);
}

/**
 * Poll the Rust Wasm decoder for aggregated Fusion metrics (Confidence, Sensors, Latency).
 * This executes the O(N) statistical bucketing logic safe from the Main Thread.
 */
function reportFusionStats(): void {
  if (!wasmDecoder || !trackData || !sabHeader) return;

  const activeCount = Atomics.load(sabHeader, HEADER_OFFSET_ACTIVE_TRACK_COUNT);
  if (activeCount === 0) return;

  try {
    const stats = wasmDecoder.get_fusion_stats(
      trackData,
      activeCount,
      Date.now() >>> 0,
    );

    postMessage({
      type: "fusion_stats",
      stats: {
        high_confidence_count: stats.high_confidence_count,
        mid_confidence_count: stats.mid_confidence_count,
        low_confidence_count: stats.low_confidence_count,
        radar_count: stats.radar_count,
        sigint_count: stats.sigint_count,
        satellite_count: stats.satellite_count,
        ew_count: stats.ew_count,
        others_count: stats.others_count,
        avg_latency_ms: stats.avg_latency_ms,
        max_latency_ms: stats.max_latency_ms,
      },
    } satisfies FusionStatsUpdateMessage);

    // Free the Wasm-memory backed object
    if (stats.free) stats.free();
  } catch (err) {
    console.error("[DataWorker] Failed to compute Fusion stats:", err);
  }
}

function stopStatsReporting(): void {
  if (statsIntervalId !== null) {
    clearInterval(statsIntervalId);
    statsIntervalId = null;
  }
}

// ── WebTransport connection ───────────────────────────────────────────────────

// buildTransportUrl and getJwtExpiryMs are imported from data-worker-logic.ts.
// buildTransportUrl is re-exported for backward compatibility with existing tests.
export { buildTransportUrl } from "./data-worker-logic";

/**
 * Schedule a `token-expiring` notification to the main thread 60 seconds
 * before the JWT expires, giving the main thread time to refresh.
 * Clears any previously scheduled timer first.
 */
function scheduleTokenExpiryNotification(token: string): void {
  if (tokenExpiryTimerId !== null) {
    clearTimeout(tokenExpiryTimerId);
    tokenExpiryTimerId = null;
  }
  const expiryMs = getJwtExpiryMs(token);
  if (expiryMs < 0) return;
  const notifyAt = expiryMs - 60_000; // 60 s before expiry
  const delay = notifyAt - Date.now();
  if (delay <= 0) {
    // Token already near or past expiry — notify immediately.
    postMessage({ type: "token-expiring" } satisfies TokenExpiringMessage);
    return;
  }
  tokenExpiryTimerId = setTimeout(() => {
    postMessage({ type: "token-expiring" } satisfies TokenExpiringMessage);
    tokenExpiryTimerId = null;
  }, delay);
}

/**
 * Connect to a WebTransport server with exponential backoff retry.
 * Never returns — loops indefinitely until the worker is terminated.
 *
 * Reference: webtransport_guidelines.md §6.3
 */
async function connectWithRetry(initialUrl: string): Promise<void> {
  // TODO(R-017): After N consecutive WebTransport failures, fall back to
  // gRPC-Web server-streaming for the hot path (required for enterprise proxy
  // environments). See v4 implementation review R-017 for specification.
  let attempt = 0;
  let transportUrl = initialUrl;

  while (true) {
    try {
      await connectWebTransport(transportUrl);
      // Clean connection close — reset attempt counter
      attempt = 0;
    } catch (_err) {
      attempt++;
      const delay = Math.min(BASE_BACKOFF_MS * Math.pow(2, attempt), MAX_BACKOFF_MS);
      postMessage({ type: "connection_status", connected: false, latency: -1 } satisfies StatusMessage);
      await sleep(delay);
    }
    // Rebuild the URL after each attempt to pick up any token refresh.
    if (currentUrl) transportUrl = buildTransportUrl(currentUrl, currentToken);
  }
}

/**
 * Establish a WebTransport connection and process datagrams until closed.
 *
 * Datagram format: N × 128-byte FlatBuffer records (N = 1–9).
 * Reference: webtransport_guidelines.md §4.2, §6.1
 */
async function connectWebTransport(url: string): Promise<void> {
  const transport = new WebTransport(url);
  activeTransport = transport;
  await transport.ready;

  if (currentToken) {
    scheduleTokenExpiryNotification(currentToken);
  }

  postMessage({ type: "connection_status", connected: true, latency: 0 } satisfies StatusMessage);
  startStatsReporting();

  const reader = transport.datagrams.readable.getReader();

  try {
    while (true) {
      const { value: datagram, done } = await reader.read();
      if (done) break;
      if (!datagram || !trackData) continue;

      datagramsReceived++;
      processDatagram(new Uint8Array(datagram));
    }
  } finally {
    reader.releaseLock();
    activeTransport = null;
    stopStatsReporting();
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

// ── Message handler ───────────────────────────────────────────────────────────

self.addEventListener("message", (event: MessageEvent<WorkerInboundMessage>) => {
  const msg = event.data;

  if (msg.type === "init") {
    sab = msg.sab;

    // Parse SAB header — max_slots is at uint32 index HEADER_OFFSET_MAX_SLOTS (= 2)
    sabHeader = new Uint32Array(sab, 0, HEADER_SIZE / 4);
    maxSlots = sabHeader[HEADER_OFFSET_MAX_SLOTS];

    // Track data starts immediately after the header + dirty bitfield
    trackData = new Uint8Array(sab, TRACK_DATA_OFFSET);

    if (msg.url) {
      // Phase 2 hot path: real WebTransport connection
      currentUrl = msg.url;
      currentToken = msg.token;
      const transportUrl = buildTransportUrl(currentUrl, currentToken);
      loadWasmDecoder().then(() => {
        connectWithRetry(transportUrl).catch((_err) => {
          postMessage({ type: "connection_status", connected: false, latency: -1 } satisfies StatusMessage);
        });
      });
    } else {
      // Stub/dev mode: generate mock data for pipeline testing
      startMockUpdates();
    }
    return;
  }

  if (msg.type === "token-refresh") {
    // Do not log the token value. (SDLC Rule 5)
    currentToken = msg.token;
    if (currentUrl) {
      // Close the active transport to force a reconnect with the refreshed token.
      // connectWithRetry catches the resulting error and retries with the updated URL.
      activeTransport?.close();
    }
  }
});

// Clean up on Worker termination
self.addEventListener("close", () => {
  stopMockUpdates();
  stopStatsReporting();
  if (tokenExpiryTimerId !== null) {
    clearTimeout(tokenExpiryTimerId);
    tokenExpiryTimerId = null;
  }
});
