// CLASSIFICATION: UNCLASSIFIED
package sensor

import (
	"fmt"
	"math"
	"time"

	commonv1 "github.com/arvinddhasmana/rtsa_webgpu/gen/go/rtsa/common/v1"
	ingestionv1 "github.com/arvinddhasmana/rtsa_webgpu/gen/go/rtsa/ingestion/v1"
	"github.com/arvinddhasmana/rtsa_webgpu/tools/simulator/internal/generator"
	"github.com/google/uuid"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// radarSensorPos is the fixed position of the simulated radar sensor (North Atlantic).
var radarSensorPos = generator.Position{Lat: 58.0, Lon: -10.0}

// trackCounters holds per-sensor sequential track counters.
var trackCounters = make(map[string]int)

// iffModes lists the IFF mode codes generated by the simulator.
var iffModes = []string{"1", "2", "3A", "3C", "4", "5"}

// GenerateRadarObservation creates a SensorObservation with a RadarTrack payload.
// All generated observations are CLASSIFICATION_LEVEL_UNCLASSIFIED.
func GenerateRadarObservation(entity *generator.SimEntity, sensorID string) *ingestionv1.SensorObservation {
trackCounters[sensorID]++
trackNum := fmt.Sprintf("TRK-%s-%06d", sensorID, trackCounters[sensorID])

// Compute range and bearing from sensor to entity.
rangNM := distanceNMFromPositions(radarSensorPos, entity.Position)
bearing := bearingFromPositions(radarSensorPos, entity.Position)

// Radar cross-section: surface -10 to 40 dBsm, air 0 to 50 dBsm.
rcs := radarCrossSection(entity)

// Track quality: 0.6 to 1.0.
quality := 0.6 + rng().Float64()*0.4

// IFF code selection.
iffCode := iffModes[rng().Intn(len(iffModes))]

// SNR: 5 to 35 dB.
snrDB := 5.0 + rng().Float64()*30.0

altMeters := entity.Position.AltM
speedKn := entity.Position.SpeedKn
heading := entity.Position.Heading

obs := &ingestionv1.SensorObservation{
ObservationId:   uuid.New().String(),
SensorId:        sensorID,
SensorType:      commonv1.SensorType_SENSOR_TYPE_RADAR,
ObservationTime: timestamppb.New(time.Now()),
Classification:  commonv1.ClassificationLevel_CLASSIFICATION_LEVEL_UNCLASSIFIED,
Position: &commonv1.Position{
Latitude:       entity.Position.Lat,
Longitude:      entity.Position.Lon,
AltitudeMeters: &altMeters,
SpeedKnots:     &speedKn,
HeadingDegrees: &heading,
},
Metadata: map[string]string{
"sim_entity_id":      entity.ID,
"sim_entity_type":    entity.EntityType.String(),
"sim_hostile_class":  entity.HostileClass.String(),
"rtsa.coverage.range_nm":      fmt.Sprintf("%.1f", 150.0), // Simulated 150NM range
"rtsa.coverage.bearing_start":  fmt.Sprintf("%.1f", 0.0),   // Full 360 scan for now
"rtsa.coverage.bearing_end":    fmt.Sprintf("%.1f", 360.0),
"rtsa.coverage.center_lat":     fmt.Sprintf("%.6f", radarSensorPos.Lat),
"rtsa.coverage.center_lon":     fmt.Sprintf("%.6f", radarSensorPos.Lon),
},
SensorData: &ingestionv1.SensorObservation_Radar{
Radar: &ingestionv1.RadarTrack{
TrackNumber:          trackNum,
RangeNm:              rangNM,
BearingDegrees:       bearing,
RadarCrossSectionDbsm: &rcs,
EntityType:           entityTypePtr(entity.EntityType),
IffCode:              &iffCode,
SnrDb:                &snrDB,
TrackQuality:         quality,
},
},
}
return obs
}

func radarCrossSection(entity *generator.SimEntity) float64 {
switch entity.EntityType {
case commonv1.EntityType_ENTITY_TYPE_AIR:
return rng().Float64() * 50 // 0-50 dBsm
default:
return -10 + rng().Float64()*50 // -10 to 40 dBsm
}
}

func entityTypePtr(et commonv1.EntityType) *commonv1.EntityType {
v := et
return &v
}

func distanceNMFromPositions(from, to generator.Position) float64 {
dLat := (to.Lat - from.Lat) * 60
cosLat := math.Cos(from.Lat * math.Pi / 180)
dLon := (to.Lon - from.Lon) * 60 * cosLat
return math.Sqrt(dLat*dLat + dLon*dLon)
}

// bearingFromPositions calculates the true initial bearing from 'from' to 'to' in degrees.
// 0° = North, 90° = East.
// Uses the standard spherical forward azimuth formula:
//
//y = sin(Δlon) × cos(lat2)
//x = cos(lat1) × sin(lat2) − sin(lat1) × cos(lat2) × cos(Δlon)
func bearingFromPositions(from, to generator.Position) float64 {
dLon := (to.Lon - from.Lon) * math.Pi / 180
fromLatRad := from.Lat * math.Pi / 180
toLatRad := to.Lat * math.Pi / 180

y := math.Sin(dLon) * math.Cos(toLatRad)
x := math.Cos(fromLatRad)*math.Sin(toLatRad) - math.Sin(fromLatRad)*math.Cos(toLatRad)*math.Cos(dLon)
brng := math.Atan2(y, x) * 180 / math.Pi
for brng < 0 {
brng += 360
}
for brng >= 360 {
brng -= 360
}
return brng
}
